### ISSUE TITLE
Default threads should be 1 not 12

### ISSUE THREAD

**Issue by tseemann** [CPTR-ReSeqTB/UVP#14]
It appears `threads: 12` is default?

**Comment by mezewudo** [comment]
Updated.

**Comment by TimHHH** [comment]
grepping "threads" or "-t" on the log file still shows many programs running on multiple threads in default (yes, default kraken threads can be adjusted in the config file):

user@login:~/UVPtest/Results/test01$ cat NC-000962-3-H37Rv_mutated_1.30.log | grep "\-t"
kraken --db /dir/References/kraken/minikraken_20171019_8GB --gzip-compressed NC-000962-3-H37Rv_mutated_1.30.1.fastq.gz NC-000962-3-H37Rv_mutated_1.30.2.fastq.gz --paired --fastq-input --threads 8 --classified-out NC-000962-3-H37Rv_mutated_1.30_classified_Reads.fastq
fastqc --extract -t 8 -o Results/test01/fastqc NC-000962-3-H37Rv_mutated_1.30.1.fastq.gz NC-000962-3-H37Rv_mutated_1.30.2.fastq.gz
bwa mem -t 8 -R @RG	ID:NC-000962-3-H37Rv_mutated_1.30	SM:NC-000962-3-H37Rv_mutated_1.30	PL:ILLUMINA Results/test01/tmp/bwa/index/ref.fa NC-000962-3-H37Rv_mutated_1.30.1.fastq.gz NC-000962-3-H37Rv_mutated_1.30.2.fastq.gz
[main] CMD: bwa mem -t 8 -R @RG	ID:NC-000962-3-H37Rv_mutated_1.30	SM:NC-000962-3-H37Rv_mutated_1.30	PL:ILLUMINA Results/test01/tmp/bwa/index/ref.fa NC-000962-3-H37Rv_mutated_1.30.1.fastq.gz NC-000962-3-H37Rv_mutated_1.30.2.fastq.gz
@PG	ID:bwa	PN:bwa	VN:0.7.12-r1039	CL:bwa mem -t 8 -R @RG	ID:NC-000962-3-H37Rv_mutated_1.30	SM:NC-000962-3-H37Rv_mutated_1.30	PL:ILLUMINA Results/test01/tmp/bwa/index/ref.fa NC-000962-3-H37Rv_mutated_1.30.1.fastq.gz NC-000962-3-H37Rv_mutated_1.30.2.fastq.gz

user@login:~/UVPtest/Results/test01$ cat NC-000962-3-H37Rv_mutated_1.30.log | grep thread
kraken --db /dir/References/kraken/minikraken_20171019_8GB --gzip-compressed NC-000962-3-H37Rv_mutated_1.30.1.fastq.gz NC-000962-3-H37Rv_mutated_1.30.2.fastq.gz --paired --fastq-input --threads 8 --classified-out NC-000962-3-H37Rv_mutated_1.30_classified_Reads.fastq
Number of threads: 6
WARN  16:26:32,730 MicroScheduler - Number of requested GATK threads 12 is more than the number of available processors on this machine 6 
INFO  16:26:32,729 MicroScheduler - Running the GATK in parallel mode with 12 total threads, 1 CPU thread(s) for each of 12 data thread(s), of 6 processors available on this machine 
WARN  16:26:32,730 MicroScheduler - Number of requested GATK threads 12 is more than the number of available processors on this machine 6 
WARN  16:27:17,454 MicroScheduler - Number of requested GATK threads 8 is more than the number of available processors on this machine 6 
INFO  16:27:17,453 MicroScheduler - Running the GATK in parallel mode with 8 total threads, 8 CPU thread(s) for each of 1 data thread(s), of 6 processors available on this machine 
WARN  16:27:17,454 MicroScheduler - Number of requested GATK threads 8 is more than the number of available processors on this machine 6 
WARN  16:28:09,831 MicroScheduler - Number of requested GATK threads 8 is more than the number of available processors on this machine 6 
INFO  16:28:09,831 MicroScheduler - Running the GATK in parallel mode with 8 total threads, 8 CPU thread(s) for each of 1 data thread(s), of 6 processors available on this machine 
WARN  16:28:09,831 MicroScheduler - Number of requested GATK threads 8 is more than the number of available processors on this machine 6 
WARN  16:30:53,869 MicroScheduler - Number of requested GATK threads 24 is more than the number of available processors on this machine 6 
INFO  16:30:53,868 MicroScheduler - Running the GATK in parallel mode with 24 total threads, 6 CPU thread(s) for each of 4 data thread(s), of 6 processors available on this machine 
WARN  16:30:53,869 MicroScheduler - Number of requested GATK threads 24 is more than the number of available processors on this machine 6 
WARN  16:31:25,158 MicroScheduler - Number of requested GATK threads 24 is more than the number of available processors on this machine 6 
INFO  16:31:25,158 MicroScheduler - Running the GATK in parallel mode with 24 total threads, 6 CPU thread(s) for each of 4 data thread(s), of 6 processors available on this machine 
WARN  16:31:25,158 MicroScheduler - Number of requested GATK threads 24 is more than the number of available processors on this machine 6

**Comment by tseemann** [comment]
```
When UVP is installed, a `config.yml` file is stored in `lib/python<version>/site-packages/uvp/config.yml`.
```

What's in your YML config file?

**Comment by TimHHH** [comment]
more ./resetqtb-uvp/uvp/config.yml
directories:
    krakendb: /home/shared_data_ghi/CWGSMTB/References/kraken/minikraken_20171019_8GB
other:
    threads: 8
