### ISSUE TITLE
QC directory

### ISSUE THREAD

**Issue by alantsangmb** [CPTR-ReSeqTB/UVP#21]
Hi, I have run 20 MTB strains using UVP and found that the result of 1 strain is located in the QC directory, while the other 19 strains are located in the Results directory.

Might I know the is the potential cause of this? 
Thanks

**Comment by alantsangmb** [comment]
I thought this is due to a directory with the same name already exists the Results directory.
 I have repeated the analysis and the results were located in the Results directory.

**Comment by mezewudo** [comment]
Good.
