### ISSUE TITLE
SNPs criteria 

### ISSUE THREAD

**Issue by alantsangmb** [CPTR-ReSeqTB/UVP#23]
Hello, I notice that one of the criteria calling the SNPs is the presence of variants on both strands for paired reads. Is it assuming the paired end reads are overlapping each other? I am curious to know if the variants would be missed when the paired reads are not overlapping.

**Comment by tseemann** [comment]
@alantsangmb No, i think it means that each base in a genome might be covered by 100 different reads (could be R1 or R2 from different reads), and one would expect ~50 fwd and 50 rev oriented reads on average. if you got 99 fwd and 1 rev that would be "questionable". it has nothing to do with overlapping of R1 and R2 from any individual read.

**Comment by alantsangmb** [comment]
It's good to know that! Thank you.
