### ISSUE TITLE
file directories

### ISSUE THREAD

**Issue by alantsangmb** [CPTR-ReSeqTB/UVP#27]
Hello, I have installed uvp via conda.

and I would like to ask where should I put the config.yml for pointing to the kraken database?
I have looked into the /envs/reseqtb-uvp, but I can't find the "script" directory like the previous version.

And I have downloaded the SnpEff H37v data manually, where should I put this data directory?
Thank you.

**Comment by alantsangmb** [comment]
Thank you so much.
I thought the config file is located in the conda environment, but it is actually in the /uvp/ directory
So UVP is now successfully installed via conda. And the config file is found in the /uvp/ directory and editable.

**Comment by dfornika** [comment]
@alantsangmb There is now a bioconda package for UVP v2.6.0. If you use that to install UVP, then the config file will be inside the environment in:

<your env>/lib/pythonX.Y/site-packages/uvp/config.yml

So if you install like this:

```
conda create -n uvp-2.6.0 uvp=2.6.0 python=3.6
conda activate uvp-2.6.0
```

...then the config file will be here:

```
miniconda3/envs/uvp-2.6.0/lib/python3.6/uvp/config.yml
```

You'll still need to follow the GATK activation and snpEff download steps as described in the current installation instructions.

As I mentioned in the comment above, the next update (v2.7.0, if accepted) will allow you to use a `-c` or `--config` flag to pass a config file from any location.
