### ISSUE TITLE
rm: cannot remove ‘Results/test/kraken/kraken.txt’: No such file or directory

### ISSUE THREAD

**Issue by matnguyen** [CPTR-ReSeqTB/UVP#4]
It seems that UVP is trying to remove a file that has already been moved. This is what I see in the log file:

```
---[ mv ]---
Command: 
mv Results/test QC

---[ rm ]---
Command: 
rm Results/test/kraken/kraken.txt

Standard Error: 
rm: cannot remove ‘Results/test/kraken/kraken.txt’: No such file or directory
```

I am running UVP with the --keepfiles flag

**Comment by mezewudo** [comment]
Seems the Kraken tool in your installation did not run as expected. Make sure you install Krkaken correctly, following their user manual and check to see it outputs the required results.

**Comment by matnguyen** [comment]
Kraken runs properly and the outputs are present. It is just that the files that are in Results/test (which include the kraken.txt) are moved to the QC directory. UVP then tries to remove Results/test/kraken/test.txt which has already been moved to QC.
