### ISSUE TITLE
Please produce a conda package

### ISSUE THREAD

**Issue by tseemann** [CPTR-ReSeqTB/UVP#7]
Due to the number of dependences it would be great if you could package it for `bioconda`

See https://bioconda.github.io/

**Comment by mezewudo** [comment]
We will look into this for the next major revisions.

**Comment by dfornika** [comment]
I'm also interested in a bioconda package. I'm actually be interested in creating a Galaxy version of this workflow, but having all the pieces available in bioconda would be a good first step.

I noticed that `fastQValidator` is listed as a dependency but there is no bioconda package. With help from @npavlovikj we've been able to package `fastQValidator`'s main dependency, `libStatGen`:

https://anaconda.org/bioconda/libstatgen

I have an open pull request to add `fastQValidator` but it seems to use a slightly non-standard build process, so it's a bit tricky to write the `build.sh` file:

https://github.com/bioconda/bioconda-recipes/pull/12319

The remaining dependencies all seem to be available on bioconda as far as I can tell.

**Comment by d-yarmosh** [comment]
Is the bioconda package available for others?

If not, is there a version of UVP capable of working with Kraken2? I am not sure I am able to find the older Kraken 0.10 version that is listed as a dependency and so I am attempting to modify the UVP source code to handle the difference in Kraken commands as well as results formatting (as needed).

**Comment by mezewudo** [comment]
The bioconda version is still work in progress, this version of UVP is tied
to Kraken 0.10.

**Comment by dfornika** [comment]
Hi @d-yarmosh. I have an open pull request here: #19 that will help prepare the project for bioconda packaging. I'll use @mezewudo 's test data to verify that the proposed changes won't affect the output or functionality of the pipeline. I hope to have a chance to do that this week.

**Comment by d-yarmosh** [comment]
Hi @dfornika, I don't suppose there's been an update? I continue to have trouble maintaining the assorted old versions of dependencies that UVP requires to run.

**Comment by dfornika** [comment]
Hello again @d-yarmosh. I apologize for not following up on this sooner. I've been busy with other work but this has been on my mind and I'll try to do the proposed test run as soon as possible so my PR can (hopefully) be merged.

But I'm curious, are you using conda to download dependencies? There are builds for `kraken-0.10.5beta` and `kraken-0.10.6` available on bioconda:

https://anaconda.org/bioconda/kraken/files

Are those not appropriate?

**Comment by d-yarmosh** [comment]
Hi dfornika,

It's really a matter of doing this for every dependency, beyond just
kraken. I'd been busy lately as well and was hoping for the easy
one-command solution. Thanks for your help and good luck working this out!
I'm sure it'a single install package will be a great benefit to all users.

**Comment by dfornika** [comment]
@d-yarmosh The `master` branch of UVP has been updated to improve portability and make installation a bit easier. The README.md file has been updated to include instructions for creating a conda environment that includes kraken and all other dependencies.

With these changes it should be possible to create a bioconda package soon.

**Comment by d-yarmosh** [comment]
Excellent news. Thanks for reaching out!

Dave

**Comment by d-yarmosh** [comment]
Perfect, thank you. Please close this.

**Comment by tseemann** [comment]
Nice work @dfornika !
